#!/bin/bash

# Переменные (изменяемые)
SHOP_NOM="35"																# Номер цеха
HOST_NAM="tl-sr-721-"${SHOP_NOM}"01"										# Имя компьютера
DESC_IN1="Yokogawa"															# Имя сетевого адаптера 1
DESC_IN2="VIPNet"															# Имя сетевого адаптера 2
DESC_IN3="LAN-bridge"														# Описание для моста 1
BRID_IN3="vmbr0"															# Имя для моста 1
ADDR_IN3="192.168.130.100"														# IP адрес для моста 1
MASK_IN3="16"																# Маска сети для моста 1
DESC_IN4="WAN-bridge"														# Описание для моста 2
BRID_IN4="vmbr1"															# Имя для моста 2
ADDR_IN4="10.17."${SHOP_NOM}".11"											# IP адрес для моста 2
GATE_IN4="10.17."${SHOP_NOM}".1"											# Гейтвей для моста 2
MASK_IN4="16"																# Маска сети для моста 2

# Переменные (статичные)
NETW_DIR="/etc/network/"													# Адрес расположения конфигурационного файла сети
BACK_DIR="/media/config_bak/"												# Адрес расположения резервных конфигурационных файлов
LOG__DIR="/media/log/"														# Адрес расположения log файлов
LOG__FIL="${LOG__DIR}01_start.log"											# Имя log файла
NETW_FIL="interfaces"														# Имя конфигурационного файла сети

# Функция для записи в лог и вывода на экран
log_message() {
    local message="[$(date '+%Y.%m.%d %H:%M:%S')] $1"
    echo "$message" | tee -a "$LOG__FIL"
}

# Проверка на root
if [ "$(id -u)" -ne 0 ]; then
    echo "Ошибка: Требуются права root!" >&2
    exit 1
fi

# Проверка и создание папки для log файла
if [ ! -d "$LOG__DIR" ]; then
    echo "Создаем папку для логов: $LOG__DIR"
    mkdir -p "$LOG__DIR"
    if [ $? -ne 0 ]; then
        echo "Ошибка: Не удалось создать папку для логов!" >&2
        exit 1
    fi
fi

# Проверка прав на запись в лог-файл
if [ ! -w "$LOG__DIR" ] 2>/dev/null; then
    echo "Ошибка: Нет прав на запись в папку логов: $LOG__DIR" >&2
    exit 1
fi

log_message "=== Начало выполнения скрипта настройки сети ==="				# Запись в лог-файл

# Проверка и создание папки для резервных копий
if [ ! -d "$BACK_DIR" ]; then
    log_message "Создаем папку для резервных копий: $BACK_DIR"				# Запись в лог-файл
    mkdir -p "$BACK_DIR"
    if [ $? -ne 0 ]; then
        log_message "Ошибка: Не удалось создать папку для резервных копий!" # Запись в лог-файл
        exit 1
    fi
    log_message "Папка для резервных копий успешно создана"					# Запись в лог-файл
else
    log_message "Папка для резервных копий уже существует: $BACK_DIR"		# Запись в лог-файл
fi

# Определяем физические интерфейсы (исключая lo)
log_message "Определение сетевых интерфейсов..."							# Запись в лог-файл
IFACES=($(ip -o link show | awk -F': ' '{print $2}' | grep -v lo))
log_message "Найдено интерфейсов: ${#IFACES[@]}"							# Запись в лог-файл
for i in "${!IFACES[@]}"; do
    log_message "  Интерфейс $((i+1)): ${IFACES[$i]}"						# Запись в лог-файл
done
if [ ${#IFACES[@]} -lt 2 ]; then
    log_message "Ошибка: Не найдено два сетевых интерфейса!"				# Запись в лог-файл
    exit 1
fi

IFACE_PH1="${IFACES[0]}"  													# Имя первого интерфейса (Yokogawa)
IFACE_PH2="${IFACES[1]}" 													# Имя Второго интерфейса (VIPNet)
log_message "Назначение интерфейсов:"										# Запись в лог-файл
log_message "  $IFACE_PH1 -> $DESC_IN1"										# Запись в лог-файл
log_message "  $IFACE_PH2 -> $DESC_IN2"										# Запись в лог-файл

BACK_FIL="${BACK_DIR}${NETW_FIL}_$(date +'%Y_%m_%d_%H_%M_%S')"				# Создание переменной для имени резервной копии
log_message "Создание резервной копии конфигурации сети: $BACK_FIL"			# Запись в лог-файл
cp "${NETW_DIR}${NETW_FIL}" "${BACK_FIL}"									# Копирование файла
if [ $? -eq 0 ]; then
    log_message "Резервная копия успешно создана"							# Запись в лог-файл
else
    log_message "Ошибка: Не удалось создать резервную копию!"				# Запись в лог-файл
    exit 1
fi

# Настройка конфигурационного файла для сети
log_message "Настройка конфигурационного файла сети: ${NETW_DIR}${NETW_FIL}"	# Запись в лог-файл
cat > "${NETW_DIR}${NETW_FIL}" <<EOF
# network interface settings; autogenerated
# Please do NOT modify this file directly, unless you know what
# you're doing.
#
# If you want to manage parts of the network configuration manually,
# please utilize the 'source' or 'source-directory' directives to do
# so.
# PVE will preserve these directives, but will NOT read its network
# configuration from sourced files, so do not attempt to move any of
# the PVE managed interfaces into external files!

auto lo
iface lo inet loopback

iface $IFACE_PH1 inet manual
# $DESC_IN1

iface $IFACE_PH2 inet manual
# $DESC_IN2

auto $BRID_IN3
iface $BRID_IN3 inet static
    address $ADDR_IN3/$MASK_IN3
    bridge-ports $IFACE_PH1
    bridge-stp off
    bridge-fd 0
	bridge_bridge_options "stp_state 0"
# $DESC_IN3

auto $BRID_IN4
iface $BRID_IN4 inet static
    address $ADDR_IN4/$MASK_IN4
	gateway $GATE_IN4
    bridge-ports $IFACE_PH2
    bridge-stp off
    bridge-fd 0
	bridge_bridge_options "stp_state 0"
# $DESC_IN4
EOF
log_message "Конфигурационный файл сети обновлен"							# Запись в лог-файл

# Меняем имя компьютера
log_message "Настройка имени компьютера: $HOST_NAM"							# Запись в лог-файл
echo "$HOST_NAM" > /etc/hostname
hostnamectl set-hostname "$HOST_NAM"
sed -i "/127.0.1.1/c\127.0.1.1\t$HOST_NAM" /etc/hosts
log_message "Имя компьютера изменено на: $HOST_NAM"							# Запись в лог-файл

# Перезапуск сети
log_message "Перезапуск сетевых служб..."									# Запись в лог-файл
systemctl restart network
if [ $? -eq 0 ]; then
    log_message "Сетевые службы успешно перезапущены"						# Запись в лог-файл
else
    log_message "Внимание: При перезапуске сетевых служб возникли проблемы" # Запись в лог-файл
fi

# Вывод информации
log_message "
=== Настройки применены ===
Хост: $HOST_NAM
Интерфейсы:
1. $IFACE_PH1 ($DESC_IN1)

2. $IFACE_PH2 ($DESC_IN2)

3. $BRID_IN3 ($DESC_IN3):
   - IP: $ADDR_IN3/$MASK_IN3
   - Физический порт: $IFACE_PH1

4. $BRID_IN4 ($DESC_IN4):
   - IP: $ADDR_IN4/$MASK_IN4
   - Gateway: $GATE_IN4
   - Физический порт: $IFACE_PH2
"
log_message "=== Скрипт настройки сети завершен ==="						# Запись в лог-файл
echo "Лог выполнения сохранен в: $LOG__FIL"